package com.healthcare;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class paciente implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public paciente() {
    }




}