package com.healthcare.pedircita;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class cita implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CITA_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "CITA_ID_GENERATOR", sequenceName = "CITA_ID_SEQ")
    private java.lang.Long id;

    public cita() {
    }
    
    public cita(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}