package com.healthcare;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class infoCita implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "INFOCITAOD_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "INFOCITAOD_ID_GENERATOR", sequenceName = "INFOCITAOD_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Fecha de la cita")
	private java.util.Date fecha;

	@org.kie.api.definition.type.Label("Doctor que le atenderá")
	private java.lang.String doctor;

	public infoCita() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.Date getFecha() {
		return this.fecha;
	}

	public void setFecha(java.util.Date fecha) {
		this.fecha = fecha;
	}

	public java.lang.String getDoctor() {
		return this.doctor;
	}

	public void setDoctor(java.lang.String doctor) {
		this.doctor = doctor;
	}

	public infoCita(java.lang.Long id, java.util.Date fecha,
			java.lang.String doctor) {
		this.id = id;
		this.fecha = fecha;
		this.doctor = doctor;
	}

}