package com.healthcare.pedircita;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class kk implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public kk() {
    }




}